name: blood_bank
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  get_it: ^8.0.0
  intl: ^0.19.0
  image_picker: ^1.1.2
  fluttertoast: ^8.2.8
  connectivity_plus: ^6.0.5
  firebase_auth: ^5.3.0
  firebase_core: ^3.5.0
  cloud_firestore: ^5.4.2
  flutter_libphonenumber: ^2.5.0
  pin_code_fields: ^8.0.1
  device_info_plus: ^10.1.2
  firebase_storage: ^12.3.1
  shared_preferences: ^2.3.2
  circular_badge_avatar: ^0.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/lato/Lato-Light.ttf
          weight: 300
        - asset: assets/fonts/lato/Lato-Regular.ttf
          weight: 400
        - asset: assets/fonts/lato/Lato-Medium.ttf
          weight: 500
        - asset: assets/fonts/lato/Lato-Black.ttf
          weight: 500
        - asset: assets/fonts/lato/Lato-Semibold.ttf
          weight: 600
        - asset: assets/fonts/lato/Lato-Bold.ttf
          weight: 700
    - family: Heebo
      fonts:
        - asset: assets/fonts/heebo/Heebo-Regular.ttf
          weight: 300
        - asset: assets/fonts/heebo/Heebo-Thin.ttf
          weight: 300
        - asset: assets/fonts/heebo/Heebo-Medium.ttf
          weight: 400
        - asset: assets/fonts/heebo/Heebo-Light.ttf
          weight: 500
        - asset: assets/fonts/heebo/Heebo-Bold.ttf
          weight: 600
        - asset: assets/fonts/heebo/Heebo-ExtraBold.ttf
          weight: 700
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/ubuntu/Ubuntu-Regular.ttf
          weight: 400
        - asset: assets/fonts/ubuntu/Ubuntu-Medium.ttf
          weight: 500
        - asset: assets/fonts/ubuntu/Ubuntu-Bold.ttf
          weight: 600
    - family: montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat ExtraLight 275.ttf
        - asset: assets/fonts/montserrat/Montserrat Light 300.ttf
        - asset: assets/fonts/montserrat/Montserrat-Regular-400.ttf
        - asset: assets/fonts/montserrat/Montserrat Medium 500.ttf
        - asset: assets/fonts/montserrat/Montserrat SemiBold 600.ttf
        - asset: assets/fonts/montserrat/Montserrat Bold 700.ttf
        - asset: assets/fonts/montserrat/Montserrat ExtraBold 800.ttf
        - asset: assets/fonts/montserrat/Montserrat Black 900.ttf